language: node_js

node_js:
  - 'node'
  - '10'
  - '8'

install:
  - npm uninstall typescript --no-save
  - npm uninstall tslint --no-save
  - npm install
  - npm install -g codecov

script:
  - npm t
  - codecov -f ./coverage/coverage-final.json
